### ISSUE TITLE
Immutable state

### ISSUE THREAD

**Issue by steveriggins** [Ben-G/Meet#4]
In reading up on Redux, immutability seems to be a big goal of the framework. It seems like in ReSwift, we are mutating existing state with the "wrapper" struct that implements all of the "Has{XYZ}" protocols.

Am I reading this correctly? What I see are reducers returning the same state, not making new, smaller states for the state the reducer managers.

Thank you for your work on this!

**Comment by Ben-G** [comment]
@steveriggins Just browsed through my remaining open issues and noticed this one. Very sorry for the super late response!

> In reading up on Redux, immutability seems to be a big goal of the framework. It seems like in ReSwift, we are mutating existing state...

When using ReSwift, it's recommended (almost required) to only store value types in the store. Because these value types have a value semantics, mutations to them are not visible to any other part of the app. Semantically this is equivalent to creating a new, copied value. You can check out a good blog post by Chris Eidhof on this issue, in case it's unclear:  http://chris.eidhof.nl/post/structs-and-mutation-in-swift/

Hope I understood your question correctly!
