### ISSUE TITLE
Updating to ReSwift?

### ISSUE THREAD

**Issue by mkauppila** [Ben-G/Meet#5]
It seems that the demo is still using the old version of the framework, the pre-merge SwiftFlow, instead of  ReSwift. So what's up with the update? Is it sill upcoming? Or has it been scrapped in favor of some other demo app?

**Comment by Ben-G** [comment]
@mkauppila Sorry for the confusion. We are working on a new example app here: https://github.com/ReSwift/GitHubBrowserExample

It will be a little bit smaller so that it's easier to understand the `ReSwift` specific aspects of the app. Once that is done I plan to come back to this repo and update it as well; but there's a little work left :)

**Comment by mkauppila** [comment]
Thanks @Ben-G. I was suspecting something like this might have happen with the demos. So I'll check out that the new demo then.

Based on a quick glance the new demo does look a lot more friendlier, less intimidating and simpler than this one so :+1:
